on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set environment variables
        run: |
          REPO_OWNER=$(echo "${GITHUB_REPOSITORY}" | cut -d '/' -f 1 | tr '[:upper:]' '[:lower:]')
          REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | cut -d '/' -f 2 | tr '[:upper:]' '[:lower:]')
          echo "REPO_OWNER=${REPO_OWNER}" >> $GITHUB_ENV
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install and run docker-slim
        run: |
          curl -sSL https://download.docker.com/linux/static/stable/x86_64/docker-slim-1.38.0.tar.gz | tar -xvz -C /usr/local/bin --strip-components=1 docker-slim/docker-slim
          chmod +x /usr/local/bin/docker-slim
          docker build -t mk .
          docker-slim build --tag mkdocs mk
          docker tag mkdocs:latest ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}:latest
          docker tag mkdocs:latest ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}:${{ github.sha }}
          docker push ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}:latest
          docker push ghcr.io/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}:${{ github.sha }}
