name: Publish to ghcr.io

on:
  push:
    branches:
    - main

jobs:
  build: 
    runs-on: ubuntu-22.04
    permissions:
      packages: write 
      contents: read

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with: 
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Project
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest, ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.run_number }}
